a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
print("addition is:", a+b)
print("subtraction is:", a-b)
print("multiplication is:", a*b)
print("division is:", a/b)